#!D:\Kairu_DS360_Projects\fourth_week_project\fraud_detection\fourth_week_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
